replicaCount: 1

image:
  repository: home-assignment-yotam
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5001

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
